### ISSUE TITLE
Distinguish between heat & cool modes in exposed 'thermostat'

### ISSUE THREAD

**Issue by craigcabrey** [amosyuen/ha-eight-sleep-climate#20]
**Is your feature request related to a problem? Please describe.**
Currently, we expose a single 'auto' mode (heat/cool) rather than distinct modes.

**Describe the solution you'd like**
Explicitly separate between heat & cool modes. Then, treat the "temperature" as the relative strength of each mode. That will help with exposing the thermostat to Google, which currently doesn't know how to handle this thermostat (e.g. it seems to get confused at a negative temperature).

We might even be able to expose it as step increments starting at 50 & in increments of 5 (or something along those lines). Then, normalize it back to values that Eight natively understands.

**Describe alternatives you've considered**
Right now Google assistant is good enough to turn it on and off. But any adjustment of the strength seems to break it.

**Additional context**

![Screenshot_20221106-175908](https://user-images.githubusercontent.com/894565/200202745-0bee74bf-d47a-4bc1-8973-bae2809aaebb.png)

**Comment by amosyuen** [comment]
> it seems to get confused at a negative temperature
> ...
> 
Right now Google assistant is good enough to turn it on and off. But any adjustment of the strength seems to break it.

Could you clarify if google assistant works for negative temperatures? What queries are you making, negative temperature queries like "Set bed heat to -100 degrees" works for me.

I considered using explicitly heat vs cool mode, my main reason I did not implement it is that now the mode would change what "set bed temperature to 50 degrees" means.

The UI is also a tough problem. We could make it from 50 to 100, but really not very intuitive for the user to think on that scale.
