### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by craigcabrey** [amosyuen/ha-eight-sleep-climate#21]
Curious if there was any interest in trying to get this upstreamed into the core eight integration. Happy to help out if so.

**Comment by amosyuen** [comment]
I'm open to it, but this implementation is kind of hacky. See problems mentioned in https://github.com/amosyuen/ha-eight-sleep-climate/issues/20, so not sure it's quite ready for mainstream HA.

**Comment by amosyuen** [comment]
Official eight sleep integration we removed so definitely not happening now
