### ISSUE TITLE
Invalid handler specified error when adding integration

### ISSUE THREAD

**Issue by alvarezb** [amosyuen/ha-eight-sleep-climate#95]
When I try to add this integration, I get the following error message:

Config flow could not be loaded: {"message":"Invalid handler specified"}

Please let me know if there are other logs or information I should provide!

**Comment by amosyuen** [comment]
This was broken since core eight_sleep was removed. Been updated to use custom repo https://github.com/lukas-clarke/eight_sleep in v3.0.0.

**Comment by gregpakes** [comment]
I am getting this issue on the latest version - Can the issue be reopened?
